### ISSUE TITLE
`break` & `next` don't work inside blocks

### ISSUE THREAD

**Issue by weakish** [deivid-rodriguez/pry-byebug#44]
```ruby
; pry
>> for i in 0..5                                                                          
 |   if i > 2 then                                                                        
 |     break                                                                              
 |   end                                                                                  
 |   puts "Value of local variable is #{i}"                                               
 | end                                                                                    
Value of local variable is 0
Value of local variable is 1
Value of local variable is 2
Value of local variable is 3
Value of local variable is 4
Value of local variable is 5
=> 0..5
```

After uninstalling pry-byebug, it works.

Pry version 0.10.1 on Ruby 2.1.4
pry-byebug 2.0.0

**Comment by micahbf** [comment]
Same goes for `next` in a block.

`Error: Cannot find local context. Did you use binding.pry?`

**Comment by dtenenba** [comment]
+1

**Comment by micahbf** [comment]
Workaround I've put in my .pryrc:

```
Pry::Commands.block_command "noconflict", "Rename step to sstep and next to nnext" do
  Pry::Commands.rename_command("nnext", "next")
  Pry::Commands.rename_command("bbreak", "break")
end

Pry::Commands.block_command "unnoconflict", "Revert to normal next and break" do
  Pry::Commands.rename_command("next", "nnext")
  Pry::Commands.rename_command("break", "bbreak")
end
```

**Comment by JonnieCache** [comment]
+1 on this

**Comment by huanzhang** [comment]
+1

**Comment by deivid-rodriguez** [comment]
Could you guys try the latest changes and confirm this is fixed?

**Comment by huanzhang** [comment]
Seems still not work~

$gem uninstall pry-byebug
$ git clone git@github.com:deivid-rodriguez/pry-byebug.git
$ gem build pry-byebug.gemspec
$ gem install pry-byebug-3.1.0.gem

$ pry
[1] pry(main)> loop do
[1] pry(main)*   puts 'bye'
[1] pry(main)*   break
[1] pry(main)*   puts 'bug!'
[1] pry(main)> end
bye
bug!
bye
bug!
bye
bug!
bye
bug!
bye
bug!
bye
bug!
...
..
.

**Comment by deivid-rodriguez** [comment]
@huanzhang Could you try again now?

**Comment by huanzhang** [comment]
@deivid-rodriguez It's fixed this time!
Sorry for the late response.

**Comment by deivid-rodriguez** [comment]
That's great to hear!
